on:
    push:
        branches:
            - main
    pull_request:

name: Continuous integration

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
        if: matrix.rust == 'stable'
      - name: Clippy
        run: cargo clippy -- -W clippy::all -A clippy::upper_case_acronyms
        if: matrix.rust == 'stable'
      - name: Build and test
        uses: actions-rs/cargo@v1
        env:
          RUST_MIN_STACK: 8388608
        with:
          command: test

  minimal-versions:
    name: minimal versions check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Remove lock
        run: rm Cargo.lock
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -Z minimal-versions

  web:
    name: web build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.47.0 # FIXME: Because of https://github.com/palfrey/maiden/issues/40
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install Cargo web
        run: which cargo-web || cargo install cargo-web --version 0.6.24
      - name: Run Cargo web
        run: cargo web build

  deploy:
    runs-on: ubuntu-latest
    needs: [web, test, minimal-versions]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.47.0 # FIXME: Because of https://github.com/palfrey/maiden/issues/40
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install Cargo web
        run: which cargo-web || cargo install cargo-web --version 0.6.24
      - name: Run Cargo web
        run: cargo web deploy --release && GIT_DEPLOY_DIR=./target/deploy ./deploy.sh