on:
    push:
        branches:
            - main
    pull_request:

name: Continuous integration

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt -- --check
        if: matrix.rust == 'stable'
      - name: Clippy
        run: cargo clippy -- -W clippy::all
        if: matrix.rust == 'stable'
      - name: Build and test
        run: cargo test
        env:
          RUST_MIN_STACK: 8388608

  minimal-versions:
    name: minimal versions check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Remove lock
        run: rm Cargo.lock
      - run: cargo build -Z minimal-versions

  web:
    name: web build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        env:
          VERSION: "v0.16.0"
      - name: Run trunk
        run: ./trunk build --release

  deploy:
    runs-on: ubuntu-latest
    needs: [web, test, minimal-versions]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        env:
          VERSION: "v0.16.0"
      - name: Run trunk
        run: ./trunk build --release --public-url /maiden
      - name: Run deploy
        run: GIT_DEPLOY_DIR=./static/dist ./deploy.sh